name    'pe-ldap'
version '0.0.1'
source 'UNKNOWN'
author 'operations'
license 'Apache License, Version 2.0'
summary 'A module to hookup torian/puppet-ldap to PE'
description 'A module to hookup torian/puppet-ldap to PE'
project_page 'UNKNOWN'

dependency 'torian/puppet-ldap', '0.1.x'
